apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dgadoy2nd-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:0b3d02c0b60536f30c9bf53b10d7e356ff9463a1@sha256:fca3023c36b4045538f98ace007ba1efcd42501febe2bc1d43bdb9a90c3bad62
          name: container-image
